### ISSUE TITLE
Textura das maquinas do Thermal bugadas

### ISSUE THREAD

**Issue by Rafaelcore** [ArtpokeBr/Pluma#12]
[
![2021-08-14_12 11 19](https://user-images.githubusercontent.com/76077254/129466155-91f0d6a2-f82e-4927-9a07-a7b5175da208.png)
]
Se desativar 
    B:squashBakedQuads nas configs do loliASM elas voltam ao normal

**Comment by ArtpokeBr** [comment]
Dessa não sabia, vou corrigir então.
