### ISSUE TITLE
Crash ao tentar quebrar o Arboreau Extractor

### ISSUE THREAD

**Issue by PrismoArc** [ArtpokeBr/Pluma#16]
Além da textura bugada já reportada, ao tentar quebrar o Arboreau Extractor com uma picareta faz com que o jogo crashe.
Parece especifico com quebrar já que com a crescent hammer não crasha.

Crash Report (_do vannila fix_):
https://pastebin.com/h2v4zhwy

![image](https://user-images.githubusercontent.com/76567258/129633584-09b48232-518a-4aa8-9008-ccd32efc9314.png)
![image](https://user-images.githubusercontent.com/76567258/129633609-43b3629c-2dc4-4601-904f-73a41ab88137.png)

_(O bug de textura não parece acontecer quando o bloco é colocado, mais ainda tá bugado no one probe)_
![image](https://user-images.githubusercontent.com/76567258/129633645-8853340c-b30f-403b-9d6a-b9c9755c6766.png)

**Comment by ArtpokeBr** [comment]
Isso é uma coisa que possivelmente eu já corrigi, depois que o próximo patch lançar, precisará de testes
