### ISSUE TITLE
Algumas recipes com output duplo ou não aceitando outros materiais

### ISSUE THREAD

**Issue by Laion21** [ArtpokeBr/Pluma#19]
![recipe 1](https://user-images.githubusercontent.com/89288047/130309766-d3b20e25-ebbe-43e8-8f26-1496d556bab7.png)
![recipe 2](https://user-images.githubusercontent.com/89288047/130309767-0252523e-981c-4cfc-813b-78ceb2ae80ea.png)
![image](https://user-images.githubusercontent.com/89288047/130309787-8703b4a8-6a6f-48a6-90f7-646f5ed73bdc.png) (só aceita esse tipo de cobalto)

**Comment by ArtpokeBr** [comment]
![image](https://user-images.githubusercontent.com/44851727/130326526-1fac6410-59d8-4346-ae74-592f9749ea38.png)
O Large Spool me parece normal, a receita está funcionando sim, mas corrigi o problema com o Coke Bricks.
