### ISSUE TITLE
Spawn de LootChests

### ISSUE THREAD

**Issue by josevictoremiliano** [ArtpokeBr/Pluma#2]
O spawn de lootChests em cavernas parece um tanto quanto spamado ou era para assim mesmo? Gerando ate dois um próximo ao outro e as em curtas distancias mais e mais. 

Consegui 11 báus alem de itens de boa andando um pouco em cavernas.
![image](https://user-images.githubusercontent.com/59773190/129207518-b45f584e-8c6d-4974-903e-b3d378c16f66.png)

**Comment by ArtpokeBr** [comment]
Corrigido no Patch 1.1, já disponível na Curse.
