### ISSUE TITLE
plant fiber não vem através da grama do minecraft, mas vem do BoP

### ISSUE THREAD

**Issue by Sterbenxy13** [ArtpokeBr/Pluma#21]
Olá, não sei se é intencional, mas durante o tempo em que joguei, não consegui plant fiber a partir da grama normal do minecraft, mas sim, apenas a partir da grama do Biomes o' plenty.

**Comment by ArtpokeBr** [comment]
Já foi reportado, e já foi corrigido, Patch 2.0 vai ficar tudo certinho :)
