### ISSUE TITLE
Sugestão: Tanned Leather redudante

### ISSUE THREAD

**Issue by PrismoArc** [ArtpokeBr/Pluma#25]
### Na fabricação de couro, faz tanned leather para fazer leather normal, e faz tanned leather de novo para mochila.

Processo anterior -> tanned leather -> Leather normal -> tanned leather de outro mod? parece bem redundante.

![javaw_gmEH32HuVf](https://user-images.githubusercontent.com/76567258/136626281-45e157d0-f7dd-46f6-b6f3-cf73d0303159.png)
![javaw_74vJvGWp6o](https://user-images.githubusercontent.com/76567258/136626284-757b94fa-40f6-4152-94e6-f5625262fe0d.png)
![image](https://user-images.githubusercontent.com/76567258/136626195-e5c19417-bea2-42ee-9d7a-e942f275b555.png)

**Comment by ArtpokeBr** [comment]
eu tentei fazer de uma forma que fizesse sentido, mas teoricamente Hide pode ser considerado a mesma coisa que Leather mesmo?
