### ISSUE TITLE
Mortar and Pile of wood bug

### ISSUE THREAD

**Issue by Lost133** [ArtpokeBr/Pluma#4]
Art nao sei se isso e um bug mas o pile of wood do pyrotech pede especificamente um mortar de darmstadtium, e ele nao tem crafting, e um mortar por exemplo de iron ou de flint, não funciona na recipe 
![image](https://user-images.githubusercontent.com/80858042/129276083-f7e92c1f-46b0-4495-99c2-5564f77854ae.png)
![image](https://user-images.githubusercontent.com/80858042/129276297-f09dfd2f-0285-44fc-bb9e-35d69bdd68a8.png)
![image](https://user-images.githubusercontent.com/80858042/129276311-74aa6f77-1eab-4d30-b5a7-47db663a603d.png)

**Comment by ArtpokeBr** [comment]
na versão mais recente isso foi corrigido viu
