### ISSUE TITLE
Crash envolvendo "Plants" e "Better Builder's Wand"

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma#48]
Ao olhar para uma planta a "Summer SnowFlakes" do "Plants" com a wand do "Better Builder's Wand" o jogo crasha

![image](https://user-images.githubusercontent.com/88991962/137921547-896a8c13-9c48-4b7c-be89-f0db9ffe2fdc.png)

versão: Beta 2.4

Sugestão: 
1- Remoção do mod "Plants"
2- Remoção da Summer SnowFlakes e de outras flores com o mesmo problema 
3- Remoção do mod "Better Builder's Wand" e troca-lo por outro mod

**Comment by ArtpokeBr** [comment]
Desabilitado ambas, pelo menos o Plants permite a desabilitação específica de plantas! então se encontrar outras, avise.
