### ISSUE TITLE
Receita irregular de plates

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma#54]
![image](https://user-images.githubusercontent.com/88991962/138136607-ed0cf351-e407-44c8-845d-af8fb223f276.png)

e 

![image](https://user-images.githubusercontent.com/88991962/138136669-611bd4f2-db67-4e36-86fa-f99254011696.png)

plates são só craftadas em uma posição especifica, uma só na lateral e outra só no meio.
Versão: Beta 2.5
Sugestão colocar shapeless ou colocar no meio como no GTNH

**Comment by ArtpokeBr** [comment]
ô Perfeccionista kkkkkk assim funciona, relaxa. a do canto que teoricamente está errada pq é gerada pelo UniDict. então fica tranquilo.
