### ISSUE TITLE
Molds

### ISSUE THREAD

**Issue by K00K13Kookie** [ArtpokeBr/Pluma#63]
O artisan's Flint Cutters é gasto inteiro para fazer os molds na Engineer's Workbench, seria bug ou é intencional?
![Foto01](https://user-images.githubusercontent.com/93493287/139755217-bb1f7761-0d20-4e4a-9fd7-0649a8ea164a.png)

**Comment by ArtpokeBr** [comment]
Acredito que os Cutters do Artisan's não estejam no OreDict, dá uma olhada na receita no JEI, mas acho que só aceita do Immersive mesmo.
