### ISSUE TITLE
Block of Steel

### ISSUE THREAD

**Issue by K00K13Kookie** [ArtpokeBr/Pluma#64]
Para fazer o craft do block of steel no compressor não está realizando o craft, pois ele pede o steel do railcraft.
![foto02](https://user-images.githubusercontent.com/93493287/139777482-461bfc9f-82f4-4983-83f0-8161d23e4b4c.png)
![foto03](https://user-images.githubusercontent.com/93493287/139777480-632e907f-596d-4c4a-95d4-872d0eac6eca.png)

**Comment by ArtpokeBr** [comment]
Ok, Erro de OreDict! será corrigido.
