### ISSUE TITLE
Crafting do Bronze Tank e Cauldron.

### ISSUE THREAD

**Issue by K00K13Kookie** [ArtpokeBr/Pluma#65]
O Bronze Tank não tem receita; ou houve algum problema de oredict na quest.
![foto04](https://user-images.githubusercontent.com/93493287/139777893-431997fa-ec7c-4dc1-ac23-ad0b4575abf9.png)

Cauldron possui duas receitas que dão a mesma coisa, sendo que uma deveria dar duas por ser um pouco mais cara.
![foto5](https://user-images.githubusercontent.com/93493287/139778027-6b53763f-0ed2-44ae-a46e-525fd553d5df.png)

**Comment by ArtpokeBr** [comment]
Aliás, obrigado por fazer os Playtests :) o Patch 3.0 vai dar uma pequena acertada na Machinery Era como um todo, deixando a progressão mais interessante e tal! :)
