### ISSUE TITLE
Plates

### ISSUE THREAD

**Issue by K00K13Kookie** [ArtpokeBr/Pluma#69]
A plate de palis ta com a recipe da plate de diamond do actually.
![01](https://user-images.githubusercontent.com/93493287/140426496-a5a54362-b79b-4d99-b846-8cdc05fc4b65.png)

A plate de Ruby e Saphira não possuem craft impossibilitando realizar alguns craftings;
![03](https://user-images.githubusercontent.com/93493287/140426311-15813345-989f-4186-9442-da45ecf60ac5.png)
![02](https://user-images.githubusercontent.com/93493287/140426316-1849ec80-c587-4db3-9417-3f9548876d78.png)

**Comment by ArtpokeBr** [comment]
A 3.0 vai chegar daquele jeito kkk obrigado por ir reportando, pq depois vou conferindo pré patch se já corrigi tudo!

**Comment by K00K13Kookie** [comment]
De nada. Estou reportando tudo que eu vejo de errado para que o próximo patch venha perfeitinho, mas claro que eu sei que tá no beta e ainda haverá bugs.
