### ISSUE TITLE
Ethanol

### ISSUE THREAD

**Issue by K00K13Kookie** [ArtpokeBr/Pluma#71]
Ethanol produzido no fermenter é diferente do que a quest pede.
![f2](https://user-images.githubusercontent.com/93493287/140582854-1a14e71e-f710-4093-860f-f17970f17fa7.png)
![f3](https://user-images.githubusercontent.com/93493287/140582858-25bd2a3a-6305-49ec-9898-b205ce1d1be3.png)

**Comment by ArtpokeBr** [comment]
Anotado!
