### ISSUE TITLE
Incoerência na quest!

### ISSUE THREAD

**Issue by K00K13Kookie** [ArtpokeBr/Pluma#72]
A quest está pedindo itens que não precisa fazer, por exemplo HV capacitor. E além disso ia ser inviável fazer o HV capacitor, pois para fazer ele precisa de aluminio e ainda nesse stage de game não existe forma de fazer.
![f04](https://user-images.githubusercontent.com/93493287/140843588-c5fc54ea-c4a0-4617-9b81-a256fbfd8822.png)
![f05](https://user-images.githubusercontent.com/93493287/140843625-b7d03f6c-2416-4253-9bbd-0864c2a275a8.png)

**Comment by ArtpokeBr** [comment]
Isso foi por causa de uma mudança recente no Immersive Tech, estava mexendo nisso hoje inclusive, vou ajustar!
