### ISSUE TITLE
Block of Steel

### ISSUE THREAD

**Issue by K00K13Kookie** [ArtpokeBr/Pluma#73]
Tá ocorrendo algum bug com o block of steel nós fazemos o do greg, mas quando fazemos as estruturas do immersive e quebramos elas para realocar em outro lugar, os blocks of steel estão virando do immersive, e por algum bug com os blocos do immersive de steel não está formando as estruturas.

**Comment by ArtpokeBr** [comment]
provavelmente por causa do fato dos blocos de steel do immersive não estarem com a OreDict. teoricamente eu removi por causa da unificação, mas pelo visto vou ter que retornar.
