### ISSUE TITLE
Erro de continuidade nas quests 

### ISSUE THREAD

**Issue by Rhuanzin121** [ArtpokeBr/Pluma#74]
Pra fazer a tailo's workbale precisa de soaking pot que usa pra fazer a treated wood.. mais nas quests a ordem está errada.
Não e nada serio. mais e meio chato pois precisa quebrar e colocar de novo e fazer outra treated wood.
![image](https://user-images.githubusercontent.com/93957919/140846158-5849690e-30d1-4ac5-8a36-1526e72c4c5c.png)

**Comment by ArtpokeBr** [comment]
Anotado como Melhoria! obrigado pelo report.

**Comment by ShiroWalkeer** [comment]
Tem um erro na progressão. Para conseguir fazer o HOP grafite nós precisamos de bloco de carvão que pode ser feito de duas maneiras. Que é no soaking pot com coal tar (que precisa queimar bloco de carvão dentro da camera com blocos refratários) que precisa de blocos de carvão para queimar então só sobra fazer da outra forma que é através do mechanical compactor. que na receita precisa de pistão que precisa de red alloy e a única forma que conseguir atualmente o red alloy foi através do kiln então talvez trocar a ordem.
![image](https://user-images.githubusercontent.com/94151924/141395331-f8987f26-225e-4122-b8a0-867d5fbd38a5.png)
