### ISSUE TITLE
Black Steel Ingot

### ISSUE THREAD

**Issue by K00K13Kookie** [ArtpokeBr/Pluma#77]
Erro de oredict dos itens usados para craftar, sendo ele o steel dust
![3](https://user-images.githubusercontent.com/93493287/141371154-e5046237-0ecb-4ce4-b84f-58ff729ad07a.png)
![1](https://user-images.githubusercontent.com/93493287/141371156-f3f1af92-ea74-4a7b-ac46-cf47f56ba31b.png)
![2](https://user-images.githubusercontent.com/93493287/141371157-6d144092-8517-4b4c-a0f3-dde9f1756f1e.png)
;

**Comment by ArtpokeBr** [comment]
Pode ser Spoiler até, mas no Próximo Patch isso tudo foi corrigido pois a progressão relacionada foi acertada :)
