### ISSUE TITLE
Plant Fiber Não dropa

### ISSUE THREAD

**Issue by C1n0xx** [ArtpokeBr/Pluma#8]
A Plant Fiber só esta dropando da short grass do BOP

**Comment by ArtpokeBr** [comment]
tem como provar isso? em testes aqui funciona normalmente, esse problema na verdade acontecia ao contrário antigamente kkk, aonde gramas do BOP que não dropavam.

**Comment by C1n0xx** [comment]
Não, o meu computador está com problemas para gravar
